"""Column Rename

Revision ID: 701528355096
Revises: 8ada39dc6900
Create Date: 2025-07-29 12:41:49.574705

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '701528355096'
down_revision: Union[str, Sequence[str], None] = '8ada39dc6900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_partner', sa.Column('serviceable_zip_codes', sa.ARRAY(sa.INTEGER()), nullable=True))
    op.drop_column('delivery_partner', 'Servicable_zip_code')
    op.alter_column('shipment', 'delivery_partner_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipment', 'delivery_partner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('delivery_partner', sa.Column('Servicable_zip_code', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('delivery_partner', 'serviceable_zip_codes')
    # ### end Alembic commands ###
